// <auto-generated />
namespace Project_sem_3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class insurancepackages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(insurancepackages));
        
        string IMigrationMetadata.Id
        {
            get { return "202003171410450_insurancepackages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
